---
# .hadolint.yaml
ignored:
  - DL3007 # Using latest is prone to errors if the image will ever update
  - DL3018 # Pin versions in apk add
  - DL3013 # Pin versions in pip install
  - DL3016 # Pin versions in npm install
