---
name: Dependabot

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automate:
    name: Automate
    uses: brixion/workflows/.github/workflows/dependabot-automate.yml@main
    secrets: inherit
